/*
 * generated by Xtext
 */
package org.regeinc.lang.scoping;

import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/** 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class ElScopeProvider extends AbstractDeclarativeScopeProvider {

}
