/*
* generated by Xtext
*/
package org.regeinc.lang.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class ElOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
