/*
 * generated by Xtext
 */
package org.regeinc.lang;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ElRuntimeModule extends org.regeinc.lang.AbstractElRuntimeModule {

}
