/*
* generated by Xtext
*/
package org.regeinc.lang.ui.contentassist;

import org.regeinc.lang.ui.contentassist.AbstractElProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ElProposalProvider extends AbstractElProposalProvider {

}
