/*
 * generated by Xtext
 */
package org.regeinc.lang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ElUiModule extends org.regeinc.lang.ui.AbstractElUiModule {
	public ElUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
